Feature/blazegraph
UUDigitalHumanitieslab/readit-interface pull request #521
Opened 2022-04-12 10:31 UTC by JeltevanBoheemen

A few things going on in this PR:

- Switch from fuseki to blazegraph
- Update rdflib to 6.X. This resolves most of the bugs we encountered upon switch to blazegraph.
- Update Python to 3.8 (consequence of rdflib update)
- Update Django to 3.2, consequence of Python 3.8, and also nice-to-have.
- Solve the multiple prefix conundrum. This turned out to be a hassle. See #520
- Slightly adjusted the ontology migrations. Turned out rdflib uses `https` for schema.org, frontend uses `http` (sigh)

To test this, you will need a virtual environment with Python 3.8.x (tested on 3.8.9). If ontology classes do not show up in the picker, clear the ontology graph and re-run `rdfmigrate`.
I'm working on the updated documentation.

Closes #520, closes #476

2022-04-12 12:17 UTC, jgonggrijp commented
Possibly helps with #139, almost certainly partly addresses #515.

2022-04-12 12:51 UTC, jgonggrijp requested changes
Kudos for getting it to work! Minor comments below.

Anything I need to know about installing Blazegraph before I try this locally (that isn't already in the Blazegraph manual)?

2022-04-12 12:51 UTC, jgonggrijp commented on backend/rdf/conftest.py
> +from rdflib import ConjunctiveGraph, Graph, Literal, URIRef
Why this order change?

2022-04-12 12:51 UTC, jgonggrijp commented on backend/readit/settings.py
> +DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
Even Django fell for the SUV hype.

2022-04-12 12:51 UTC, jgonggrijp commented on backend/sparql/views.py
> +                    querystring)
Is 56 characters already too long?

2022-04-12 13:00 UTC, JeltevanBoheemen commented on backend/rdf/baseclasses.py
> +from django.utils.functional import classproperty
Agreed

2022-04-12 13:02 UTC, JeltevanBoheemen commented on backend/rdf/utils.py
> +            graph, triple[0], graphs_applied_to, privileged_predicates)
I find this weirdly formatted as well. And it shouldn't have been, I only auto-format my own code.

2022-04-12 13:03 UTC, JeltevanBoheemen commented on backend/sparql/constants.py
> +SPARQL_NS = '{}/sparql'.format(settings.RDF_NAMESPACE_ROOT)
Oh right! This is a leftover from a bogus initNs. Instead of including nonsense I included the url of the sparql api.

2022-04-12 13:04 UTC, JeltevanBoheemen commented on backend/sparql/views.py
> +                raise APIException(u_h_e)
I agree, it felt a bit dirty writing ANOTHER HttpError clause. Decided on paying attention to more pressing matters though. I'll see if I can cook something up.

2022-04-12 13:06 UTC, JeltevanBoheemen commented on backend/rdf/utils_test.py
> +    assert stripped_res == stripped_query
Good point. I'll add these cases. And will add a query with double prefix declarations. This is possible when you include a prefix in the frontend sparql query, that is already in the list of standard prefixes. So not too theoretic a case.

2022-04-12 13:08 UTC, JeltevanBoheemen commented
Apologies for the oversight on auto-formatting. I set it to 'only changed code' a while ago and got lazy checking changes before staging.

Follow the blazegraph quickstart and add namespaces `readit` and `readit-test`. Both in `quads` mode.

2022-04-12 14:01 UTC, jgonggrijp commented on backend/sparql/constants.py
> +SPARQL_NS = '{}/sparql'.format(settings.RDF_NAMESPACE_ROOT)
Clever!

2022-04-13 15:03 UTC, jgonggrijp commented
Quick update on testing at my end:

- Installing Blazegraph went smoothly (after I figured out that I needed the latest release candidate because all previous versions didn't support Java 17).
- Installing the updated dependencies in a new Python 3.8 venv proved challenging; `keepalive` refused to install on the grounds that `use_2to3 is invalid`. After a lot of going back and forth between conflicting recommendations on the web, I was able to install everything by downgrading `setuptools` to `<58`.
- After this, `yarn django check` ran without errors but `yarn test-back` did not. Turned out that I needed to a newer version of PostgreSQL (still using 9.4). I'm now in the process of installing PostgreSQL 14.

2022-04-13 16:43 UTC, jgonggrijp commented
Another update: I successfully installed PostgreSQL 14 and migrated my data (which was a bit of a hassle). Most backend tests pass now, except for the new `test_prefix_injection`.

In the first assertion that `res == prefixed_query`, the equation fails because `res` has many prefixes, while `prefixed_query` only has `rdf` and `rdfs`. Did you do anything in particular to prevent this problem, @JeltevanBoheemen? Maybe an uncommitted change?

I'll hold off on further testing until this is resolved.

2022-04-14 11:52 UTC, JeltevanBoheemen commented
> Another update: I successfully installed PostgreSQL 14 and migrated my data (which was a bit of a hassle). Most backend tests pass now, except for the new `test_prefix_injection`.
Did not realise this. I use PostgreSQL 13, because this is what most of our servers run. Good to realise that this can have an effect on the code.
> In the first assertion that `res == prefixed_query`, the equation fails because `res` has many prefixes, while `prefixed_query` only has `rdf` and `rdfs`. Did you do anything in particular to prevent this problem, @JeltevanBoheemen? Maybe an uncommitted change?
> 
> I'll hold off on further testing until this is resolved.
Thanks for clearing this up. Turns out SPARQLStore keeps a rolling dictionary of nsBinding, I suspect all common namespaces occurring in triples in the store. I only ran the test in isolation. I'll adapt the test.

2022-04-14 11:54 UTC, JeltevanBoheemen commented
> Quick update on testing at my end:
> 
> * Installing Blazegraph went smoothly (after I figured out that I needed the latest release candidate because all previous versions didn't support Java 17).

Great
> * Installing the updated dependencies in a new Python 3.8 venv proved challenging; `keepalive` refused to install on the grounds that `use_2to3 is invalid`. After a lot of going back and forth between conflicting recommendations on the web, I was able to install everything by downgrading `setuptools` to `<58`.

This is unfortunate. As we discussed, this is best solved by installing a specific version in the deployment script. I'll make sure the documentation mentions this.

2022-04-14 12:32 UTC, JeltevanBoheemen commented
>Installing the updated dependencies in a new Python 3.8 venv proved challenging; keepalive refused to install on the grounds >that use_2to3 is invalid. After a lot of going back and forth between conflicting recommendations on the web, I was able to >install everything by downgrading setuptools to <58.

I removed the `keepalive` dependency. It was used in `sparqlwrapper`, which was earlier removed. Keep-alive is default in `urllib3`. With these changes I was able to `yarn install-back` on a fresh virtual environment without problems.

2022-05-03 12:42 UTC, JeltevanBoheemen commented
> > Another update: I successfully installed PostgreSQL 14 and migrated my data (which was a bit of a hassle). Most backend tests pass now, except for the new `test_prefix_injection`.
> 
> Did not realise this. I use PostgreSQL 13, because this is what most of our servers run. Good to realise that this can have an effect on the code.
> 
> > In the first assertion that `res == prefixed_query`, the equation fails because `res` has many prefixes, while `prefixed_query` only has `rdf` and `rdfs`. Did you do anything in particular to prevent this problem, @JeltevanBoheemen? Maybe an uncommitted change?
> > I'll hold off on further testing until this is resolved.
> 
> Thanks for clearing this up. Turns out SPARQLStore keeps a rolling dictionary of nsBinding, I suspect all common namespaces occurring in triples in the store. I only ran the test in isolation. I'll adapt the test.

I fixed this issue.

2022-05-11 08:37 UTC, merged