Rename Node to Subject
UUDigitalHumanitieslab/readit-interface pull request #605
Opened 2024-03-13 16:42 UTC by tijmenbaarda

Renamed the `Node` class to `Subject`, both in code and in comments.

I also renamed a few related function and variable names, but there may be some left that I did not spot. I did not rename `Nodeish` and `NodeLike`.

I have used automatic renaming from an IDE, which seemed to work well. I have checked the results by hand and the tests are still running and the interface is still working, but I am not sure if there are things that I didn't think of.

2024-03-14 17:44 UTC, jgonggrijp requested changes
My compliments to your IDE, which seems to have done the job *almost* without breaking anything, and to you for your daring willingness to take on this task. The diff looks very good to me.

Besides reading the diff, I consulted `grep` to check for any remaining occurrences of `node` or `Node`. It turns out there are quite a lot. A few of them refer to Node.js, a node in a datastructure or the built-in (DOM) `Node` type, but most refer to the class that is now `Subject`. For consistency, it would be best if you could rename the remaining occurrences as well. I will list them here to save you some of the effort of running `grep` again and having to decide for each occurrence whether it refers to `Subject` or not:

- [ ] in `category-colors/category-colors-view-test.ts`:
    - [ ] `getDefaultNode`
    - [ ] `node1`
    - [ ] `node2`
- [ ] `NodeMap` in `common-adapters/flat-item-model-test.ts`
- [ ] in `common-adapters/flat-item-model.ts`:
    - [ ] `receiveTopNode`
    - [ ] `rotateNode`
    - [ ] `oldNode`
    - [ ] `newNode`
- [ ] `someNode` in a comment in `common-rdf/ns.ts`
- [ ] in `common-rdf/subject.ts`:
    - [ ] `NodeGetOptions`
    - [ ] `NodeLike` (as you already noticed)
    - [ ] `id2node`
- [ ] `Nodeish` (which you noticed) in `hierarchy/ontology.ts` should probably be renamed to something like `Item` or `Entry`
- [ ] `nodeType` in `panel-search-results/search-result-list-panel.ts` (also occurs in template literal)
- [ ] `Node` (!) in `panel-source-list/source-list-panel` on line 87
- [ ] in `panel-source-list/source-summary-view.ts`:
    - [ ] `titleNode`
    - [ ] `authorNode`
    - [ ] `textNode`
- [ ] in `sparql/compile-query.ts`, with corresponding templates in `query-templates/*`:
    - [ ] `countNodesQuery` and `countNodesTemplate`
    - [ ] `nodesByUserQuery` and `nodesByUserTemplate`
    - [ ] `randomNodesQuery` and `randomNodesTemplate`
- [ ] `idAsNode` in `utilities/interpret-text-test.ts`
- [ ] `getDefaultNode` in `utilities/linked-data-utilities-test.ts`
- [ ] `aNode` in a comment in `utilities/linked-data-utilities.ts`
- [ ] `nodes` as a variable name in `utilities/relation-utilities-test.ts` on lines 47 and 48
- [ ] `node` is all over the place as a variable name. `node` and its plurals `nodes` and `Nodes` also occur a lot in comments and strings. The only places within `/frontend/src` where you should ***not*** replace these words by the corresponding variant of `[sS]ubjects?` are the following:
    - `forms/ontology-class-picker-view.ts` (refers to datastructure nodes)
    - `hierarchy/hierarchy-view.ts` (likewise)
    - `hierarchy/ontology.ts` (likewise, could optionally rename the variables to `item` or `entry` to match the new name for `Nodeish`)
    - `sparql/query-templates/random-nodes-template.hbs` in the comment on line 5 (refers to RDF nodes in the strict sense, i.e., not necessarily subjects)

When `[nN]ode` appears embedded in a larger word but I did not list it above, there is a small probability that I missed it, but more likely it should not be replaced. For example, `childNodes` in `hightlight/chunk-consistency-test.ts` refers to DOM nodes.

If, after seeing the above list, the task seems too daunting, please let me know!

2024-03-27 12:41 UTC, tijmenbaarda commented
I have now renamed the remaining relevant cases of `node` and combinations with `Node` and `node`. For `Nodeish` I opted for `Item`.

Building works and tests run, and I hope that I did not rename any node that is not related to RDF.

2024-03-27 17:06 UTC, jgonggrijp reviewed
You did rename a few non-RDF nodes, but not many; see comments. Regardless, I'm impressed!

2024-03-28 13:43 UTC, jgonggrijp approved these changes

2024-03-28 13:47 UTC, merged