Upgrade to Elasticsearch 8
UUDigitalHumanitieslab/readit-interface pull request #614
Opened 2024-06-13 11:53 UTC by BeritJanssen

This PR includes the necessary steps to upgrade from Elasticsearch 7 to 8. Adjusting the Python versions seemed somewhat difficult: I had to pin the django-allauth library to a lower version to be able to run without the "Improperly configured" error locally. I can roll this back if needed.

I still did not get the application running locally. It seems the rdfmigrate does not work (whole output below). I hope that this is a known problem, and can be circumvented. At least the Elasticsearch setup works this way.

If my local problems won't matter for deployment on the server, the steps to upgrade to ES8 are as follows:
- merge 
- merge this branch
- deploy

```
Apply all migrations: account, admin, auth, authtoken, contenttypes, feedback, items, nlp_ontology, rdflib_django, sessions, sites, socialaccount, sources
2024-06-13 13:37:16 Running migrations:
2024-06-13 13:37:16   No migrations to apply.
2024-06-13 13:37:16   Your models in app(s): 'rdflib_django' have changes that are not yet reflected in a migration, and so won't be applied.
2024-06-13 13:37:16   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
2024-06-13 13:35:15     if x not in other:
2024-06-13 13:35:15   File "/usr/local/lib/python3.9/site-packages/rdflib/graph.py", line 555, in __contains__
2024-06-13 13:35:15     for triple in self.triples(triple):
2024-06-13 13:35:15   File "/usr/local/lib/python3.9/site-packages/rdflib/graph.py", line 466, in triples
2024-06-13 13:35:15     for (s, p, o), cg in self.__store.triples((s, p, o), context=self):
2024-06-13 13:35:15   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlstore.py", line 286, in triples
2024-06-13 13:35:15     result = self._query(
2024-06-13 13:35:15   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlstore.py", line 160, in _query
2024-06-13 13:35:15     return super(SPARQLStore, self).query(*args, **kwargs)
2024-06-13 13:35:15   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlconnector.py", line 110, in query
2024-06-13 13:35:15     raise ValueError(
2024-06-13 13:35:15 ValueError: You did something wrong formulating either the URI or your SPARQL query
2024-06-13 13:37:17 Traceback (most recent call last):
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlconnector.py", line 106, in query
2024-06-13 13:37:17     res = urlopen(
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
2024-06-13 13:37:17     return opener.open(url, data, timeout)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
2024-06-13 13:37:17     response = meth(req, response)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
2024-06-13 13:37:17     response = self.parent.error(
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
2024-06-13 13:37:17     return self._call_chain(*args)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
2024-06-13 13:37:17     result = func(*args)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
2024-06-13 13:37:17     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2024-06-13 13:37:17 urllib.error.HTTPError: HTTP Error 404: 
2024-06-13 13:37:17 
2024-06-13 13:37:17 During handling of the above exception, another exception occurred:
2024-06-13 13:37:17 
2024-06-13 13:37:17 Traceback (most recent call last):
2024-06-13 13:37:17   File "/usr/src/app/manage.py", line 21, in <module>
2024-06-13 13:37:17     main()
2024-06-13 13:37:17   File "/usr/src/app/manage.py", line 17, in main
2024-06-13 13:37:17     execute_from_command_line(sys.argv)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
2024-06-13 13:37:17     utility.execute()
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
2024-06-13 13:37:17     self.fetch_command(subcommand).run_from_argv(self.argv)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
2024-06-13 13:37:17     self.execute(*args, **cmd_options)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
2024-06-13 13:37:17     output = self.handle(*args, **options)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdf/management/commands/rdfmigrate.py", line 34, in handle
2024-06-13 13:37:17     self.migrate_package(app)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdf/management/commands/rdfmigrate.py", line 43, in migrate_package
2024-06-13 13:37:17     self.migrate_graph(migrations.Migration())
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdf/management/commands/rdfmigrate.py", line 58, in migrate_graph
2024-06-13 13:37:17     additions = desired - actual
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/graph.py", line 642, in __sub__
2024-06-13 13:37:17     if x not in other:
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/graph.py", line 555, in __contains__
2024-06-13 13:37:17     for triple in self.triples(triple):
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/graph.py", line 466, in triples
2024-06-13 13:37:17     for (s, p, o), cg in self.__store.triples((s, p, o), context=self):
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlstore.py", line 286, in triples
2024-06-13 13:37:17     result = self._query(
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlstore.py", line 160, in _query
2024-06-13 13:37:17     return super(SPARQLStore, self).query(*args, **kwargs)
2024-06-13 13:37:17   File "/usr/local/lib/python3.9/site-packages/rdflib/plugins/stores/sparqlconnector.py", line 110, in query
2024-06-13 13:37:17     raise ValueError(
2024-06-13 13:37:17 ValueError: You did something wrong formulating either the URI or your SPARQL query
```

2024-06-19 12:55 UTC, jgonggrijp requested changes
Thanks for fixing this!

Regarding the errors you were seeing: was Blazegraph running and did you create a namespace?

2024-07-04 09:39 UTC, BeritJanssen commented on backend/readit/elasticsearch.py
> +        pass
No, the scheme needs to be 'http' (i.e., unchanged) when there is no information to make the connection via SSL.

2024-07-04 09:51 UTC, BeritJanssen commented on backend/scripts/sources_to_elasticsearch.py
> +from readit.elasticsearch import get_elasticsearch_client
Good catch! This was an effect of the isort plugin. I deactivated that now, as it actually didn't even do what it should (i.e., standard library imports first).

2024-07-04 09:52 UTC, merged

2024-07-04 09:53 UTC, BeritJanssen commented
> @BeritJanssen I'm going to review now. Did you run into those problems with or without Docker?

This was indeed *with* Docker.

2024-07-04 11:03 UTC, jgonggrijp commented on backend/readit/elasticsearch.py
> +        pass
Is line 21 still above lines 22 and 23? Because then you're going to have HTTPS even when there is no SSL information.